export const routes = [
  { url: "/" },
  { url: "/about/" },
  { url: "/contact/" },
  { url: "/cv/" },
  { url: "/blog/1/" },
  { url: "/blog/10/" },
  { url: "/blog/11/" },
  { url: "/blog/12/" },
  { url: "/blog/13/" },
  { url: "/blog/14/" },
  { url: "/blog/15/" },
  { url: "/blog/16/" },
  { url: "/blog/17/" },
  { url: "/blog/18/" },
  { url: "/blog/19/" },
  { url: "/blog/2/" },
  { url: "/blog/20/" },
  { url: "/blog/3/" },
  { url: "/blog/4/" },
  { url: "/blog/5/" },
  { url: "/blog/6/" },
  { url: "/blog/7/" },
  { url: "/blog/8/" },
  { url: "/blog/9/" },
];
